name: ptx-sandbox
services:
  mongodb-sandbox:
    container_name: "mongodb-sandbox"
    image: ptx/mongodb:8.0.5-slim
    # noinspection ComposeUnknownKeys
    attach: false
    restart: no
    networks:
      - core
    healthcheck:
      test: [ "CMD-SHELL", "curl -sSf http://localhost:27017 || exit 1" ]
      start_period: 30s
      start_interval: 3s
    profiles:
      - mocked
  mongo-seed:
    container_name: "mongodb-seed"
    image: ptx-sandbox/mongo-seed:1.9.8-slim
    depends_on:
      mongodb-sandbox:
        condition: service_healthy
    networks:
      - core
    profiles:
      - mocked
  ######################################################################################################################
  provider:
    container_name: "provider-pdc"
    image: ptx/connector:1.9.8-slim
    restart: no
    volumes:
      - './rsc/provider.config.json:/usr/src/app/dist/src/config.production.json'
      - './rsc/.env.provider:/usr/src/app/.env.production'
    ports:
      - "3010:3000"
    environment:
      MONGO_URI: mongodb://mongodb-sandbox:27017/provider
    depends_on:
      mongo-seed:
        condition: service_completed_successfully
      catalog:
        condition: service_started
    networks:
      - core
      - provider-nw
    profiles:
      - mocked
  consumer:
    container_name: "consumer-pdc"
    image: ptx/connector:1.9.8-slim
    restart: no
    volumes:
      - './rsc/consumer.config.json:/usr/src/app/dist/src/config.production.json'
      - './rsc/.env.consumer:/usr/src/app/.env.production'
    ports:
      - "3011:3000"
    environment:
      MONGO_URI: mongodb://mongodb-sandbox:27017/consumer
    depends_on:
      mongo-seed:
        condition: service_completed_successfully
      catalog:
        condition: service_started
    networks:
      - core
      - consumer-nw
    profiles:
      - mocked
  ######################################################################################################################
  contract:
    container_name: "ptx-contract"
    image: ptx-sandbox/contract:1.9.8-slim
    restart: no
    ports:
      - "3001:8081"
    extra_hosts:
      - "gw.ptx-edge.cluster.k3d:host-gateway"
    networks:
      - core
  catalog:
    container_name: "ptx-catalog"
    image: ptx-sandbox/catalog:1.9.8-slim
    restart: no
    ports:
      - "3002:8082"
    extra_hosts:
      - "gw.ptx-edge.cluster.k3d:host-gateway"
    networks:
      - core
  consent:
    container_name: "ptx-consent"
    image: ptx-sandbox/consent:1.9.8-slim
    restart: no
    ports:
      - "3003:8083"
    extra_hosts:
      - "gw.ptx-edge.cluster.k3d:host-gateway"
    networks:
      - core
networks:
  core:
    external: false
  provider-nw:
    external: false
  consumer-nw:
    external: false