apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-pvc
  namespace: ptx-edge
  annotations:
    defaultVolumeType: local
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: batch/v1
kind: Job
metadata:
  name: consumer
  namespace: ptx-edge
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  template:
    spec:
      initContainers:
        - name: builder
          image: registry.k3d.local:5000/ptx-edge/builder:1.0
          imagePullPolicy: IfNotPresent
          command: [ "python3", "-m", "app"]
          volumeMounts:
            - name: builder-src
              mountPath: /usr/src/builder/app
            - name: worker-dir
              mountPath: /usr/src/worker
              readOnly: false
            - name: data-dir
              mountPath: /var/cache/data
              readOnly: false
      containers:
        - name: worker
          image: registry.k3d.local:5000/busybox:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c" ]
          args:
            - echo "=== worker started ===";
              echo ">>> INPUTS";
              ls -hl /usr/src/worker /var/cache/data;
              echo -e "\n@@@ Generating results...\n";
              sleep 5s;
              echo "Result created" >> /var/cache/result/result.txt;
              echo ">>> OUTPUTS";
              ls -hl /var/cache/result;
              echo "=== worker ended ===";
          volumeMounts:
            - name: worker-dir
              mountPath: /usr/src/worker
              readOnly: true
            - name: data-dir
              mountPath: /var/cache/data
              readOnly: true
            - name: result-dir
              mountPath: /var/cache/result
              readOnly: false
      restartPolicy: OnFailure
      volumes:
        - name: builder-src
          hostPath:
            path: /usr/local/share/builder/app
            type: Directory
        - name: data-dir
          emptyDir:
            sizeLimit: 100Mi
        - name: worker-dir
          emptyDir:
            sizeLimit: 100Mi
        - name: result-dir
          persistentVolumeClaim:
            claimName: worker-pvc