---
apiVersion: v1
kind: Pod
metadata:
  name: builder2
  namespace: ptx-edge
  labels:
    app: builder2
    env: test
spec:
  serviceAccountName: builder
  initContainers:
    - name: builder
      image: registry.k3d.local:5000/ptx-edge/builder:1.0
      imagePullPolicy: IfNotPresent
      #command: [ "python3", "-m", "app", "-v"]
      command: [ "/bin/sh", "-c", "sleep infinity" ]
      volumeMounts:
        - name: src
          mountPath: /usr/src/builder/app
        - name: worker-dir
          mountPath: /usr/src/worker
          readOnly: false
        - name: data-dir
          mountPath: /var/cache/data
          readOnly: false
        - name: kube-api-client-cfg
          mountPath: /var/run/secrets/projected
          readOnly: true
        - name: registry-ca
          mountPath: /usr/share/ca-certificates/ptx-edge/registry_CA.crt
          readOnly: true
      ports:
        - name: webhook-port
          containerPort: 9999
          protocol: TCP
      envFrom:
        - secretRef:
            name: pdc-secrets.env
        - configMapRef:
            name: pdc-config.env
      env:
        #- name: BUILD_PDC_HOST
        #  value: ${PDC}-${PZ_DATA_0}.${PTX}.svc.cluster.local
        #- name: BUILD_PDC_PORT
        #  value: "${PDC_PORT}"
        #- name: BUILD_PDC_KEY_SERVICE
        #  valueFrom:
        #    secretKeyRef:
        #      name: ${PDC}-secrets-env
        #      key: SERVICE_KEY
        #- name: BUILD_PDC_KEY_SECRET
        #  valueFrom:
        #    secretKeyRef:
        #      name: ${PDC}-secrets-env
        #      key: SECRET_KEY
        - name: BUILD_PDC_SYNC_ENABLED
          value: "true"
        - name: BUILD_PDC_SYNC_LOCK
          value: "pdc-sync-lock"
        #- name: BUILD_CONNECTION_TIMEOUT
        #  value: "${BUILD_TIMEOUT}"
        - name: BUILD_DATA_METHOD
          value: "ptx"
          #- name: BUILD_DATA_SRC
          #value: "file:///etc/hostname"  # collect_data_from_file
          #value: "https://github.com/czeni/sample-datasets/raw/refs/heads/main/mnist_train_data.npz"  # collect_data_from_url
          #value: "http://host.k3d.internal:9000/datetime.txt" # collect_data_from_url + auth
          #value: "https://host.k3d.internal:9443/static/dp1/train_data.npz" # collect_data_from_url + https + insecure
          #value: "https://host.k3d.internal:9443/dataset/dp1/train_data.npz" # collect_data_from_url + https + insecure + auth
          #value: "ptx://66db1a6dc29e3ba863a85e0f"
        #- name: BUILD_DATA_AUTH
        #  value: "basic:demo:demo"
        #- name: BUILD_DATA_AUTH_SCHEME
        #  value: basic
        #- name: BUILD_DATA_AUTH_USER
        #  value: demo
        #- name: BUILD_DATA_AUTH_SECRET
        #  value: demo
        - name: BUILD_DATA_AUTH_INSECURE
          value: "true"
        - name: BUILD_DATA_DST
          value: "/var/cache/data/"
        #- name: BUILD_PTX_DATA_EXCHANGE_CONTRACT
        #  value: "https://contract.visionstrust.com/contracts/${PTX_CONTRACT_ID}"
        #- name: BUILD_PTX_DATA_EXCHANGE_DATA_OFFER
        #  value: "https://api.visionstrust.com/v1/catalog/serviceofferings/${PTX_DATA_OFFER_ID}"
        #- name: BUILD_PTX_DATA_EXCHANGE_DATA_RESOURCE
        #  value: "https://api.visionstrust.com/v1/catalog/dataresources/${PTX_DATA_ID}"
        #- name: BUILD_PTX_DATA_EXCHANGE_SERVICE_OFFER
        #  value: "https://api.visionstrust.com/v1/catalog/serviceofferings/${PTX_SERVICE_OFFER_ID}"
        #- name: BUILD_PTX_DATA_EXCHANGE_SERVICE_RESOURCE
        #  value: "https://api.visionstrust.com/v1/catalog/softwareresources/${PTX_SERVICE_ID}"
        #- name: BUILD_WORKER_METHOD
        #  value: "SKIP"
        - name: BUILD_WORKER_SRC
          value: "docker://busybox:latest"  # collect_worker_image_from_repo
          #value: "docker://host.k3d.internal:5555/busybox:latest" # collect_worker_image_from_repo + auth
          #value: "docker://czentye/worker:latest" # collect_worker_image_from_repo + auth
          #value: "secret://czentye/worker:latest" # create_image_pull_secret from auth
        #- name: BUILD_WORKER_AUTH
        #  value: "czentye:${DH_TOKEN}@https://index.docker.io/v1/"
        #- name: BUILD_WORKER_AUTH_SERVER
        #  value: "https://host.k3d.internal:5555"
        #- name: BUILD_WORKER_AUTH_USER
        #  value: "czentye"
        #  value: "mock"
        #- name: BUILD_WORKER_AUTH_SECRET
        #  value: "${DH_TOKEN}"
        #  value: "mock"
        #- name: BUILD_WORKER_AUTH_INSECURE
        #  value: "true"
        #  value: "false"
        #- name: BUILD_WORKER_AUTH_CADIR
        #  value: "..."
        - name: BUILD_WORKER_DST
          value: "myworker:latest"
  volumes:
    - name: src
      hostPath:
        path: /usr/local/share/ptx-edge/builder/app
        type: Directory
    - name: registry-ca
      hostPath:
        path: /usr/share/ca-certificates/ptx-edge/registry_CA.crt
        type: File
    - name: data-dir
      emptyDir:
        sizeLimit: 100Mi
    - name: worker-dir
      emptyDir:
        sizeLimit: 100Mi
    - name: kube-api-client-cfg
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
  containers:
    - name: worker
      image: k8s.gcr.io/pause
  restartPolicy: Never