apiVersion: v1
kind: ConfigMap
metadata:
  name: pdc-config
  namespace: ptx-edge
data:
  .env: |
    NODE_ENV=production
    PORT=3000
    SESSION_SECRET=abc
    SESSION_COOKIE_EXPIRATION=24000
    MONGO_URI=mongodb://pdc.localhost:27017/dataspace-connector
    WINSTON_LOGS_MAX_FILES=14d
    WINSTON_LOGS_MAX_SIZE=20m
    JWT_BEARER_TOKEN_EXPIRATION=3h
    JWT_REFRESH_TOKEN_EXPIRATION=1d
  config.json: |
    {
      "endpoint": "http://pdc-zone-a.ptx-edge.svc.cluster.local:30003/",
      "serviceKey": "dWJUUKH9rYF9wr_UAPb6PQXW9h17G7dzuGCbiDhcyjCGgHzLwBp6QHOQhDg0FFxS24GD8nvw37oe_LOjl7ztNATYiVOd_ZEVHQpV",
      "secretKey": "Qh4XvuhSJbOp8nMV1JtibAUqjp3w_efBeFUfCmqQW_Nl8x4t3Sk6fWiK5L05CB3jhKZOgY5JlBSvWkFBHH_6fFhYQZWXNoZxO78x",
      "contractUri": "http://contract.ptx-sandbox.svc.cluster.local:3001/",
      "catalogUri": "http://catalog.ptx-sandbox.svc.cluster.local:3002/v1/",
      "consentUri": "http://consent.ptx-sandbox.svc.cluster.local:3003/v1/",
      "expressLimitSize": "100mb"
    }
immutable: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdc
  namespace: ptx-edge
  labels:
    app: pdc
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-creator
  namespace: ptx-edge
rules:
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-creator
  namespace: ptx-edge
subjects:
  - kind: ServiceAccount
    name: pdc
    namespace: ptx-edge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-lister
  namespace: ptx-edge
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-lister
  namespace: ptx-edge
subjects:
  - kind: ServiceAccount
    name: pdc
    namespace: ptx-edge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-lister
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pdc
  namespace: ptx-edge
  labels:
    app: pdc
spec:
  selector:
    matchLabels:
      app: pdc
  template:
    metadata:
      labels:
        app: pdc
    spec:
      nodeSelector:
        connector.dataspace.ptx.org/enabled: "true"
      serviceAccountName: pdc
      initContainers:
        - name: builder
          image: registry.k3d.local:5000/ptx-edge/builder:1.0
          imagePullPolicy: IfNotPresent
          command: [ "python3", "-m", "app.tools.pdc-init", "-v", "--type=clusterip", "--port=3000" ]
          #command: [ "python3", "-m", "app.tools.pdc-init", "-v", "--force", "--type=clusterip", "--port=3000" ]
          #command: [ "/bin/sh", "-c", "sleep infinity" ]
          volumeMounts:
            - name: src
              mountPath: /usr/src/builder/app
            - name: kube-api-client-cfg
              mountPath: /var/run/secrets/projected
              readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        - name: pdc-mongodb
          image: registry.k3d.local:5000/ptx/mongodb:8.0.5-slim
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo-port
              containerPort: 27017
          restartPolicy: Always # Native sidecar container
      containers:
        - name: ptx-connector
          image: registry.k3d.local:5000/ptx/connector:1.9.5-slim
          imagePullPolicy: IfNotPresent
          ports:
            - name: pdc-port
              containerPort: 3000
              protocol: TCP
              hostPort: 30003
          volumeMounts:
            - name: pdc-env
              mountPath: "/usr/src/app/.env.production"
              subPath: .env.production
              readOnly: true
            - name: pdc-config
              mountPath: "/usr/src/app/dist/src/config.production.json"
              subPath: config.production.json
              readOnly: true
          command: [ "npm", "run", "start" ]
      volumes:
        - name: pdc-env
          configMap:
            name: pdc-config
            items:
              - key: .env
                path: .env.production
        - name: pdc-config
          configMap:
            name: pdc-config
            items:
              - key: config.json
                path: config.production.json
        - name: src
          hostPath:
            path: /usr/local/share/builder/app
            type: Directory
        - name: kube-api-client-cfg
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
---
apiVersion: v1
kind: Service
metadata:
  name: pdc-zone-a
  namespace: ptx-edge
spec:
  selector:
    app: pdc
    privacy-zone.dataspace.ptx.org/zone-A: "true"
  type: ClusterIP
  ports:
    - name: pdc-port
      port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pdc-zone-b
  namespace: ptx-edge
spec:
  selector:
    app: pdc
    privacy-zone.dataspace.ptx.org/zone-B: "true"
  type: ClusterIP
  ports:
    - name: pdc-port
      port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pdc-zone-a
  namespace: ptx-edge
  labels:
    app: pdc
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/ptx-edge/zone-a/pdc`)
      kind: Rule
      middlewares:
        - name: pdc-zone-a-stripprefix
      services:
        - name: pdc-zone-a
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pdc-zone-a-stripprefix
  labels:
    app: pdc
spec:
  stripPrefix:
    prefixes:
      - /ptx-edge/zone-a/pdc
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pdc-zone-b
  namespace: ptx-edge
  labels:
    app: pdc
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/ptx-edge/zone-b/pdc`)
      kind: Rule
      middlewares:
        - name: pdc-zone-b-stripprefix
      services:
        - name: pdc-zone-b
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pdc-zone-b-stripprefix
  labels:
    app: pdc
spec:
  stripPrefix:
    prefixes:
      - /ptx-edge/zone-b/pdc
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: pdc
#  labels:
#    app: pdc
#  annotations:
#    ingress.kubernetes.io/ssl-redirect: "false"
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: pdc-zone-a
#            port:
#              number: 3000