apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-pvc
  namespace: ptx-edge
  annotations:
    defaultVolumeType: local
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: batch/v1
kind: Job
metadata:
  name: consumer
  namespace: ptx-edge
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      initContainers:
        - name: builder
          image: registry.k3d.local:5000/ptx-edge/builder:1.0
          imagePullPolicy: IfNotPresent
          #command: [ "/bin/sh", "-c", "wget -P ${BUILD_DATA_DST} ${BUILD_DATA_SRC}" ]
          command: [ "python3", "-m", "app" ]
          volumeMounts:
            - name: builder-src
              mountPath: /usr/src/builder/app
            - name: data-dir
              mountPath: /var/cache/data
              readOnly: false
          env:
            - name: BUILD_DATA_SRC
              value: "https://github.com/czeni/sample-datasets/raw/refs/heads/main/mnist_train_data.npz"
            - name: BUILD_DATA_DST
              value: "/var/cache/data"
      containers:
        - name: worker
          image: registry.k3d.local:5000/samples/convnet-worker:0.1
          imagePullPolicy: IfNotPresent
          command: [ "python3", "-m", "app.training_worker" ]
          volumeMounts:
            - name: data-dir
              mountPath: /var/cache/data
              readOnly: true
            - name: result-dir
              mountPath: /var/cache/result
              readOnly: false
          env:
            - name: TASK_DATA_SRC
              value: "/var/cache/data/mnist_train_data.npz"
            - name: TASK_DATA_DST
              value: "/var/cache/result/convnet_model.keras"
      restartPolicy: OnFailure
      volumes:
        - name: builder-src
          hostPath:
            path: /usr/local/share/builder/app
            type: Directory
        - name: data-dir
          emptyDir:
            sizeLimit: 100Mi
        - name: result-dir
          persistentVolumeClaim:
            claimName: worker-pvc