apiVersion: v1
kind: Pod
metadata:
  name: rest-api
  namespace: ptx-edge
  labels:
    app: rest-api
spec:
  containers:
    - name: rest-api
      image: registry.k3d.local:5000/ptx-edge/rest-api:1.0
      imagePullPolicy: IfNotPresent
      command: [ "uvicorn", "app.main:app", "--host=0.0.0.0", "--port=8080", "--workers=2",
                 "--reload", "--reload-dir=app", "--access-log", "--log-level=debug" ]
      env:
        - name: ROOT_PATH
          value: "/ptx-edge/api/v1"
      ports:
        - name: api-port
          containerPort: 8080
      volumeMounts:
        - name: src
          mountPath: /usr/src/rest-api/app
  volumes:
    - name: src
      hostPath:
        path: /usr/local/share/rest-api/app
        type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api
  namespace: ptx-edge
spec:
  selector:
    app: rest-api
  type: ClusterIP
  ports:
    - name: api-port
      port: 8080
      targetPort: api-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-api
  namespace: ptx-edge
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /ptx-edge/api/v1
            pathType: Prefix
            backend:
              service:
                name: rest-api
                port:
                  number: 8080
