openapi: 3.1.0
info:
  title: PTX Edge Computing REST-API
  description: The Edge Computing (Decentralized AI processing) BB-02 provides value-added
    services exploiting an underlying distributed edge computing infrastructure.
  contact:
    email: czentye.janos@vik.bme.hu
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
  x-creation-date: '2025-09-11T15:12:05'
servers:
- url: /
  description: PTX Edge Computing
paths:
  /versions:
    get:
      summary: Get Versions
      description: Versions of the REST-API component
      operationId: get_versions_versions_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionsResponse'
    head:
      summary: Get Versions
      description: Versions of the REST-API component
      operationId: get_versions_versions_head
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionsResponse'
  /health:
    get:
      summary: Health
      description: For health check purposes
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    head:
      summary: Health
      description: For health check purposes
      operationId: health_health_head
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    VersionsResponse:
      properties:
        api:
          type: string
          title: Api
        framework:
          type: string
          title: Framework
      type: object
      required:
      - api
      - framework
      title: VersionsResponse
tags:
- name: customerAPI
  description: Customer-facing API (EdgeAPI)
  external_docs:
    description: Prometheus-X
    url: https://github.com/Prometheus-X-association/edge-computing
