# coding: utf-8

# flake8: noqa

"""
    Edge Computing REST-API

    The Edge Computing (Decentralized AI processing) BB-02 provides value-added services exploiting an underlying distributed edge computing infrastructure.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: czentye.janos@vik.bme.hu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.customer_api_api import CustomerAPIApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.execution_metrics import ExecutionMetrics
from swagger_client.models.execution_request_body import ExecutionRequestBody
from swagger_client.models.execution_result import ExecutionResult
from swagger_client.models.metadata import Metadata
from swagger_client.models.private_execution_request_body import PrivateExecutionRequestBody
from swagger_client.models.private_execution_result import PrivateExecutionResult
