---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${BUILDER}
  namespace: ${PTX}
  labels:
    app.kubernetes.io/name: ${BUILDER}
    env: ${ENV}
    tier: edge
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${BUILDER}-rbac
  namespace: ${PTX}
  labels:
    app.kubernetes.io/name: ${BUILDER}
    env: ${ENV}
    tier: edge
rules:
  - apiGroups: [ "" ]
    resources: [ secrets ]
    verbs: [ create ]
  - apiGroups: [ coordination.k8s.io ]
    resources: [ leases ]
    verbs: [ get, create, update ]
  - apiGroups: [ "" ]
    resources: [ configmaps ]
    verbs: [ get, create, update ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${BUILDER}-rbac
  namespace: ${PTX}
  labels:
    app.kubernetes.io/name: ${BUILDER}
    env: ${ENV}
    tier: edge
subjects:
  - kind: ServiceAccount
    name: ${BUILDER}
    namespace: ${PTX}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${BUILDER}-rbac
---