# coding: utf-8

"""
    Edge Computing REST-API

    The Edge Computing (Decentralized AI processing) BB-02 provides value-added services exploiting an underlying distributed edge computing infrastructure.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: czentye.janos@vik.bme.hu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customer_api_api import CustomerAPIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomerAPIApi(unittest.TestCase):
    """CustomerAPIApi unit test stubs"""

    def setUp(self):
        self.api = CustomerAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_request_edge_proc(self):
        """Test case for request_edge_proc

        Execute function on data  # noqa: E501
        """
        pass

    def test_request_privacy_edge_proc(self):
        """Test case for request_privacy_edge_proc

        Execute function on private data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
