# coding: utf-8

"""
    Edge Computing REST-API

    The Edge Computing (Decentralized AI processing) BB-02 provides value-added services exploiting an underlying distributed edge computing infrastructure.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: czentye.janos@vik.bme.hu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.consent_id import ConsentID  # noqa: E501
from swagger_client.rest import ApiException


class TestConsentID(unittest.TestCase):
    """ConsentID unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsentID(self):
        """Test ConsentID"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.consent_id.ConsentID()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
