[app]
name = "builder"

[env]
prefix = "BUILD_"

[connection]
timeout = 30
retry = 3

[data]
dst = "/var/cache/data/"

[worker]
app = "worker"
pull-secret = "worker-pull-cred"

[registry]
url = "registry.k3d.local:5000"

[registry.auth]
cred = "admin:admin"
insecure = "False"
ca_dir = "/usr/share/ca-certificates/ptx-edge/"