[app]
name = "builder"

[env]
prefix = "BUILD_"

[connection]
timeout = 30
retry = 3

[data]
dst = "/var/cache/data/"

[worker]
app = "worker"
pull-secret = "worker-pull-cred"

[registry.auth]
server = "registry.k3d.local:5000"
user = "admin"
secret = "admin"
insecure = "no"
ca_dir = "/usr/share/ca-certificates/ptx-edge/"