[app]
name = "builder"

[env]
prefix = "BUILD_"

[connection]
timeout = 30
retry = 3

[data]
dst = "/var/cache/data/"

[worker]
app = "worker"

[registry]
url = "registry.k3d.local:5000"
ca_dir = "/usr/share/ca-certificates/ptx-edge"