# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.contract_id import ContractID  # noqa: F401,E501
from swagger_server.models.data_id import DataID  # noqa: F401,E501
from swagger_server.models.function_id import FunctionID  # noqa: F401,E501
from swagger_server import util


class ExecutionRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, function: FunctionID=None, data: DataID=None, data_contract: ContractID=None, func_contract: ContractID=None):  # noqa: E501
        """ExecutionRequestBody - a model defined in Swagger

        :param function: The function of this ExecutionRequestBody.  # noqa: E501
        :type function: FunctionID
        :param data: The data of this ExecutionRequestBody.  # noqa: E501
        :type data: DataID
        :param data_contract: The data_contract of this ExecutionRequestBody.  # noqa: E501
        :type data_contract: ContractID
        :param func_contract: The func_contract of this ExecutionRequestBody.  # noqa: E501
        :type func_contract: ContractID
        """
        self.swagger_types = {
            'function': FunctionID,
            'data': DataID,
            'data_contract': ContractID,
            'func_contract': ContractID
        }

        self.attribute_map = {
            'function': 'function',
            'data': 'data',
            'data_contract': 'data_contract',
            'func_contract': 'func_contract'
        }
        self._function = function
        self._data = data
        self._data_contract = data_contract
        self._func_contract = func_contract

    @classmethod
    def from_dict(cls, dikt) -> 'ExecutionRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExecutionRequestBody of this ExecutionRequestBody.  # noqa: E501
        :rtype: ExecutionRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def function(self) -> FunctionID:
        """Gets the function of this ExecutionRequestBody.


        :return: The function of this ExecutionRequestBody.
        :rtype: FunctionID
        """
        return self._function

    @function.setter
    def function(self, function: FunctionID):
        """Sets the function of this ExecutionRequestBody.


        :param function: The function of this ExecutionRequestBody.
        :type function: FunctionID
        """

        self._function = function

    @property
    def data(self) -> DataID:
        """Gets the data of this ExecutionRequestBody.


        :return: The data of this ExecutionRequestBody.
        :rtype: DataID
        """
        return self._data

    @data.setter
    def data(self, data: DataID):
        """Sets the data of this ExecutionRequestBody.


        :param data: The data of this ExecutionRequestBody.
        :type data: DataID
        """

        self._data = data

    @property
    def data_contract(self) -> ContractID:
        """Gets the data_contract of this ExecutionRequestBody.


        :return: The data_contract of this ExecutionRequestBody.
        :rtype: ContractID
        """
        return self._data_contract

    @data_contract.setter
    def data_contract(self, data_contract: ContractID):
        """Sets the data_contract of this ExecutionRequestBody.


        :param data_contract: The data_contract of this ExecutionRequestBody.
        :type data_contract: ContractID
        """

        self._data_contract = data_contract

    @property
    def func_contract(self) -> ContractID:
        """Gets the func_contract of this ExecutionRequestBody.


        :return: The func_contract of this ExecutionRequestBody.
        :rtype: ContractID
        """
        return self._func_contract

    @func_contract.setter
    def func_contract(self, func_contract: ContractID):
        """Sets the func_contract of this ExecutionRequestBody.


        :param func_contract: The func_contract of this ExecutionRequestBody.
        :type func_contract: ContractID
        """

        self._func_contract = func_contract
