name: pdc
services:
  connector:
    container_name: pdc-connector
    image: ptx/connector:1.9.2-slim
    restart: unless-stopped
    volumes:
      - './config.production.json:/usr/src/app/dist/src/config.production.json'
      - './.env.production:/usr/src/app/.env.production'
    ports:
      - "3333:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/dataspace-connector
    extra_hosts:
      - "gw.ptx-core.sandbox.local:host-gateway"
    networks:
      - local
    depends_on:
      mongodb:
        condition: service_healthy
      catalog:
        condition: service_healthy
    healthcheck:
      test: [ "NONE" ]
  mongodb:
    container_name: pdc-mongodb
    image: ptx/mongodb:8.0.5-slim
    ports:
      - "27018:27017"
    networks:
      - local
    healthcheck:
      test: [ "CMD-SHELL", "curl -sSf http://localhost:27017 || exit 1" ]
      start_period: 30s
      start_interval: 3s
  catalog:
    container_name: ptx-catalog
    image: ptx-sandbox/catalog:1.9.2-slim
    ports:
      - "3002:8082"
    extra_hosts:
      - "gw.ptx-edge.cluster.k3s:host-gateway"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -O /dev/null http://localhost:8082/__admin/health || exit 1" ]
      start_period: 30s
      start_interval: 3s
networks:
  local:
    external: false