apiVersion: dataspace.ptx.org/v1alpha1
kind: EdgeWorkerTask
metadata:
  name: test-ewt
  labels:
    env: test
spec:
  service:
    enabled: true
    interfaces:
      - port: 8080
      - port: 80
        public: true
  data:
    src:
      scheme: https
      path: "https://github.com:8080/czeni/sample-datasets/raw/refs/heads/main/mnist_train_data.npz"
      auth:
        method: basic
        user: admin
        secret: admin
    dst:
      scheme: local
      path: "/var/cache/data/"
  worker:
    location:
      protocol: docker
      image: "busybox:latest"
      cred:
        server: "https://index.docker.io/v1/"
        user: admin
        secret: admin
        insecure: false
    cached: true
    name: "myworker:latest"
    command: [ "/bin/bash", "date" ]
    config:
      file:
        path: "/var/cache/worker/config.json"
        data: |
          {
            "test": 42
          }
      env:
        - key: WRK_TEST_VAR
          value: "test123"
  dataspace:
    offer:
      provider: 66d187f4ee71f9f096bae8ca
      consumer: 66d18b79ee71f9f096baecb1