# coding: utf-8

"""
    Edge Computing REST-API

    The Edge Computing (Decentralized AI processing) BB-02 provides value-added services exploiting an underlying distributed edge computing infrastructure.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: czentye.janos@vik.bme.hu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExecutionMetrics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ret': 'int',
        'elapsed_time': 'int'
    }

    attribute_map = {
        'ret': 'ret',
        'elapsed_time': 'elapsedTime'
    }

    def __init__(self, ret=None, elapsed_time=None):  # noqa: E501
        """ExecutionMetrics - a model defined in Swagger"""  # noqa: E501
        self._ret = None
        self._elapsed_time = None
        self.discriminator = None
        if ret is not None:
            self.ret = ret
        if elapsed_time is not None:
            self.elapsed_time = elapsed_time

    @property
    def ret(self):
        """Gets the ret of this ExecutionMetrics.  # noqa: E501

        Return value of the function  # noqa: E501

        :return: The ret of this ExecutionMetrics.  # noqa: E501
        :rtype: int
        """
        return self._ret

    @ret.setter
    def ret(self, ret):
        """Sets the ret of this ExecutionMetrics.

        Return value of the function  # noqa: E501

        :param ret: The ret of this ExecutionMetrics.  # noqa: E501
        :type: int
        """

        self._ret = ret

    @property
    def elapsed_time(self):
        """Gets the elapsed_time of this ExecutionMetrics.  # noqa: E501

        Elapsed time of the function  # noqa: E501

        :return: The elapsed_time of this ExecutionMetrics.  # noqa: E501
        :rtype: int
        """
        return self._elapsed_time

    @elapsed_time.setter
    def elapsed_time(self, elapsed_time):
        """Sets the elapsed_time of this ExecutionMetrics.

        Elapsed time of the function  # noqa: E501

        :param elapsed_time: The elapsed_time of this ExecutionMetrics.  # noqa: E501
        :type: int
        """

        self._elapsed_time = elapsed_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExecutionMetrics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExecutionMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
