# coding: utf-8

"""
    Edge Computing REST-API

    The Edge Computing (Decentralized AI processing) BB-02 provides value-added services exploiting an underlying distributed edge computing infrastructure.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: czentye.janos@vik.bme.hu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PrivateExecutionRequestBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'function': 'str',
        'private_data': 'str',
        'data_contract': 'str',
        'func_contract': 'str',
        'consent': 'str',
        'token': 'str',
        'metadata': 'Metadata'
    }

    attribute_map = {
        'function': 'function',
        'private_data': 'private_data',
        'data_contract': 'data_contract',
        'func_contract': 'func_contract',
        'consent': 'consent',
        'token': 'token',
        'metadata': 'metadata'
    }

    def __init__(self, function=None, private_data=None, data_contract=None, func_contract=None, consent=None, token=None, metadata=None):  # noqa: E501
        """PrivateExecutionRequestBody - a model defined in Swagger"""  # noqa: E501
        self._function = None
        self._private_data = None
        self._data_contract = None
        self._func_contract = None
        self._consent = None
        self._token = None
        self._metadata = None
        self.discriminator = None
        self.function = function
        self.private_data = private_data
        self.data_contract = data_contract
        self.func_contract = func_contract
        self.consent = consent
        self.token = token
        if metadata is not None:
            self.metadata = metadata

    @property
    def function(self):
        """Gets the function of this PrivateExecutionRequestBody.  # noqa: E501

        Unique reference/ID of the function to be applied to the private data  # noqa: E501

        :return: The function of this PrivateExecutionRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._function

    @function.setter
    def function(self, function):
        """Sets the function of this PrivateExecutionRequestBody.

        Unique reference/ID of the function to be applied to the private data  # noqa: E501

        :param function: The function of this PrivateExecutionRequestBody.  # noqa: E501
        :type: str
        """
        if function is None:
            raise ValueError("Invalid value for `function`, must not be `None`")  # noqa: E501

        self._function = function

    @property
    def private_data(self):
        """Gets the private_data of this PrivateExecutionRequestBody.  # noqa: E501

        Unique reference/ID of the data  # noqa: E501

        :return: The private_data of this PrivateExecutionRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._private_data

    @private_data.setter
    def private_data(self, private_data):
        """Sets the private_data of this PrivateExecutionRequestBody.

        Unique reference/ID of the data  # noqa: E501

        :param private_data: The private_data of this PrivateExecutionRequestBody.  # noqa: E501
        :type: str
        """
        if private_data is None:
            raise ValueError("Invalid value for `private_data`, must not be `None`")  # noqa: E501

        self._private_data = private_data

    @property
    def data_contract(self):
        """Gets the data_contract of this PrivateExecutionRequestBody.  # noqa: E501

        Unique contract ID  # noqa: E501

        :return: The data_contract of this PrivateExecutionRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._data_contract

    @data_contract.setter
    def data_contract(self, data_contract):
        """Sets the data_contract of this PrivateExecutionRequestBody.

        Unique contract ID  # noqa: E501

        :param data_contract: The data_contract of this PrivateExecutionRequestBody.  # noqa: E501
        :type: str
        """
        if data_contract is None:
            raise ValueError("Invalid value for `data_contract`, must not be `None`")  # noqa: E501

        self._data_contract = data_contract

    @property
    def func_contract(self):
        """Gets the func_contract of this PrivateExecutionRequestBody.  # noqa: E501

        Unique contract ID  # noqa: E501

        :return: The func_contract of this PrivateExecutionRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._func_contract

    @func_contract.setter
    def func_contract(self, func_contract):
        """Sets the func_contract of this PrivateExecutionRequestBody.

        Unique contract ID  # noqa: E501

        :param func_contract: The func_contract of this PrivateExecutionRequestBody.  # noqa: E501
        :type: str
        """
        if func_contract is None:
            raise ValueError("Invalid value for `func_contract`, must not be `None`")  # noqa: E501

        self._func_contract = func_contract

    @property
    def consent(self):
        """Gets the consent of this PrivateExecutionRequestBody.  # noqa: E501

        Unique consent ID  # noqa: E501

        :return: The consent of this PrivateExecutionRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._consent

    @consent.setter
    def consent(self, consent):
        """Sets the consent of this PrivateExecutionRequestBody.

        Unique consent ID  # noqa: E501

        :param consent: The consent of this PrivateExecutionRequestBody.  # noqa: E501
        :type: str
        """
        if consent is None:
            raise ValueError("Invalid value for `consent`, must not be `None`")  # noqa: E501

        self._consent = consent

    @property
    def token(self):
        """Gets the token of this PrivateExecutionRequestBody.  # noqa: E501

        Unique token created by the DataProvider related to the user's consent  # noqa: E501

        :return: The token of this PrivateExecutionRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this PrivateExecutionRequestBody.

        Unique token created by the DataProvider related to the user's consent  # noqa: E501

        :param token: The token of this PrivateExecutionRequestBody.  # noqa: E501
        :type: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def metadata(self):
        """Gets the metadata of this PrivateExecutionRequestBody.  # noqa: E501


        :return: The metadata of this PrivateExecutionRequestBody.  # noqa: E501
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this PrivateExecutionRequestBody.


        :param metadata: The metadata of this PrivateExecutionRequestBody.  # noqa: E501
        :type: Metadata
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PrivateExecutionRequestBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrivateExecutionRequestBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
