---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: ${TRAEFIK}
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--providers.kubernetescrd=true"
      - "--providers.kubernetesingress=true"
      - "--providers.kubernetesgateway=true"
      - "--api.disabledashboardad=true"
      - "--api.insecure=false"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.web.http.redirections.entrypoint.permanent=true"
      - "--log.level=INFO"
      - "--accesslog=true"
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`${TRAEFIK_DASHBOARD_DOMAIN}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
        entryPoints:
          - websecure
        middlewares:
          - name: dashboard-auth
    extraObjects:
      - apiVersion: v1
        kind: Secret
        metadata:
          name: dashboard-auth-secret
        type: Opaque
        data:
          users: ${TRAEFIK_DASHBOARD_CREDS}
      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: dashboard-auth
        spec:
          basicAuth:
            secret: dashboard-auth-secret
---