apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--log.level=INFO"
      - "--api.dashboard=false"
      - "--global.sendanonymoususage=false"
