---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: ${TRAEFIK}
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log.level=DEBUG"
      #- "--accesslog=true"
      - "--providers.kubernetescrd=true"
      - "--providers.kubernetesingress=true"
      - "--providers.kubernetesgateway=true"
      - "--api=true"
      - "--api.insecure=false"
      - "--api.disabledashboardad=true"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.web.http.redirections.entrypoint.priority=42"
      - "--entryPoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.domains[0].main=${GW_TLS_DOMAIN}"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.options=kube-system-tls-opt@kubernetescrd"
      - "--certificatesresolvers.letsencrypt.acme.email=czentye.janos@vik.bme.hu"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" #Testing
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    extraObjects:
      - apiVersion: traefik.io/v1alpha1
        kind: TLSOption
        metadata:
          name: tls-opt
          namespace: kube-system
        spec:
          minVersion: VersionTLS12
          cipherSuites:
            - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
            - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
            - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
            - TLS_AES_256_GCM_SHA384
            - TLS_AES_128_GCM_SHA256
            - TLS_CHACHA20_POLY1305_SHA256
            - TLS_FALLBACK_SCSV
          curvePreferences:
            - CurveP521
            - CurveP384
          sniStrict: false
    #  - apiVersion: v1
    #    kind: Secret
    #    metadata:
    #      name: dashboard-auth-secret
    #    type: Opaque
    #    data:
    #      users: ${TRAEFIK_DASHBOARD_CREDS}
    #  - apiVersion: traefik.io/v1alpha1
    #    kind: Middleware
    #    metadata:
    #      name: dashboard-auth
    #    spec:
    #      basicAuth:
    #        secret: dashboard-auth-secret
    #ingressRoute:
    #  dashboard:
    #    enabled: true
    #    matchRule: Host(`${TRAEFIK_DASHBOARD_DOMAIN}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    #    entryPoints:
    #      - websecure
    #    middlewares:
    #      - name: dashboard-auth
---