#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ${API}
#  namespace: ${DEF_NS}
#  annotations:
#    ingress.kubernetes.io/ssl-redirect: "false"
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /${DEF_NS}/${API}/${API_VER}
#            pathType: Prefix
#            backend:
#              service:
#                name: ${API}
#                port:
#                  number: ${API_PORT}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ${API}
  namespace: ${DEF_NS}
  labels:
    app: ${API}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/${DEF_NS}/${API}/${API_VER}`)
      kind: Rule
      services:
        - name: ${API}
          port: ${API_PORT}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ${API}-secure
  namespace: ${DEF_NS}
  labels:
    app: ${API}
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/${DEF_NS}/${API}/${API_VER}`)
      kind: Rule
      services:
        - name: ${API}
          port: ${API_PORT}
  tls:
    secretName: api-tls