[ req ]
default_bits        = 4096
distinguished_name  = req_distinguished_name
req_extensions      = req_ext
prompt              = no

[ req_distinguished_name  ]
C   = EU
O   = PTX
OU  = edge
CN  = ${GW_DOMAIN}

[ req_ext ]
subjectAltName  = @alt_names

[ alt_names ]
DNS.2   = ${GW_DOMAIN}
DNS.1   = ${LB_DOMAIN}
