# generated by datamodel-codegen:
#   filename:  edgeworkertask.json
#   timestamp: 2026-02-16T13:18:17+00:00

from typing import Any

from pydantic import BaseModel


class EdgeWorkerTask(BaseModel):
    spec: Spec
    status: Status | None = None


class Spec(BaseModel):
    src: dict[str, Any]
    dst: dict[str, Any]


class Status(BaseModel):
    ready: str | None = None
