# generated by datamodel-codegen:
#   filename:  edgeworkertask.json
#   timestamp: 2026-05-08T11:39:15+00:00
#   version:   0.56.1

from typing import ClassVar
from typing import Annotated, Literal
from pydantic import BaseModel as _BaseModel, ConfigDict, Field, SecretStr
from enum import StrEnum


class BaseModel(_BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )


class EWT(BaseModel):
    # Resource specification parameters from CustomResourceDefinition
    group: ClassVar[str] = "dataspace.ptx.org"
    version: ClassVar[str] = "v1alpha1"
    kind: ClassVar[str] = "EdgeWorkerTask"
    plural: ClassVar[str] = "edgeworkertasks"
    singular: ClassVar[str] = "edgeworkertask"
    # Unique resource identification
    SELECTOR: ClassVar[tuple[str, str, str]] = (group, version, plural)
    #
    spec: EWTSpec
    """
    Specification of PTX Edge Task
    """
    status: EWTStatus | None = None
    """
    Runtime information
    """


class EWTSpec(BaseModel):
    service: EWTSpecService | None = None
    """
    Initiate worker as a service, not a single-executed task
    """
    data: EWTSpecData
    """
    Data collection parameters
    """
    worker: EWTSpecWorker
    """
    Worker environment parameters
    """
    dataspace: EWTSpecDataspace | None = None
    """
    Attributes of data exchange via PTX dataspace
    """


class EWTSpecData(BaseModel):
    src: EWTSpecDataSrc
    """
    Data source location
    """
    dst: EWTSpecDataDst | None = None
    """
    Data destination location
    """


class EWTSpecDataDst(BaseModel):
    scheme: Literal["local"] | None = "local"
    """
    Data propagation scheme
    """
    path: Annotated[
        str,
        Field(
            examples=["https://my.api.localhost:8080/data/example.csv"],
            pattern="^([^:/]+://)?([^:/]+(:[0-9]{1,5})?)?(/.+)$",
        ),
    ]
    """
    Data resource location

    Example: 'https://my.api.localhost:8080/data/example.csv'
    """
    auth: EWTSpecDataDstAuth | None = None
    """
    Authentication parameters for remote data storage
    """


class EWTSpecDataDstAuth(BaseModel):
    method: Annotated[EWTSpecDataDstAuthMethod, Field(examples=["basic"])]
    """
    Used authentication method

    Example: 'basic'
    """
    user: Annotated[str, Field(examples=["admin"], min_length=1)]
    """
    User identification

    Example: 'admin'
    """
    secret: Annotated[SecretStr, Field(examples=["myPasswd!007"], min_length=1)]
    """
    Secret token or password

    Example: 'myPasswd!007'
    """


class EWTSpecDataDstAuthMethod(StrEnum):
    BASIC = "basic"
    DIGEST = "digest"
    BEARER = "bearer"


class EWTSpecDataSrc(BaseModel):
    scheme: Annotated[EWTSpecDataSrcScheme | None, Field(examples=["https"])] = None
    """
    Data collection scheme

    Example: 'https'
    """
    path: Annotated[
        str,
        Field(
            examples=["https://my.api.localhost:8080/data/example.csv"],
            pattern="^([^:/]+://)?([^:/]+(:[0-9]{1,5})?)?(/.+)$",
        ),
    ]
    """
    Data resource location

    Example: 'https://my.api.localhost:8080/data/example.csv'
    """
    auth: EWTSpecDataSrcAuth | None = None
    """
    Authentication parameters for remote data collection
    """


class EWTSpecDataSrcAuth(BaseModel):
    method: Annotated[EWTSpecDataSrcAuthMethod, Field(examples=["basic"])]
    """
    Used authentication method

    Example: 'basic'
    """
    user: Annotated[str, Field(examples=["admin"], min_length=1)]
    """
    User identification

    Example: 'admin'
    """
    secret: Annotated[SecretStr, Field(examples=["myPasswd!007"], min_length=1)]
    """
    Secret token or password

    Example: 'myPasswd!007'
    """


class EWTSpecDataSrcAuthMethod(StrEnum):
    BASIC = "basic"
    DIGEST = "digest"
    BEARER = "bearer"


class EWTSpecDataSrcScheme(StrEnum):
    FILE = "file"
    DIR = "dir"
    HTTP = "http"
    HTTPS = "https"
    PTX = "ptx"


class EWTSpecDataspace(BaseModel):
    offer: EWTSpecDataspaceOffer | None = None
    """
    PTX dataspace contract info
    """


class EWTSpecDataspaceOffer(BaseModel):
    provider: Annotated[str, Field(min_length=1)]
    """
    Data provider ID
    """
    consumer: Annotated[str, Field(min_length=1)]
    """
    Data consumer ID
    """


class EWTSpecService(BaseModel):
    enabled: bool
    """
    Enable service creation
    """
    interfaces: list[EWTSpecServiceInterface] | None = None
    """
    Exposed worker interfaces
    """


class EWTSpecServiceInterface(BaseModel):
    port: Annotated[int, Field(examples=[8080], ge=1, le=65535)]
    """
    Service port

    Example: 8080
    """
    public: bool | None = False
    """
    Enable out-of-cluster access
    """
    secured: bool | None = False
    """
    Apply the same security measures as of the REST-API, e.g., authentication
    """


class EWTSpecWorker(BaseModel):
    location: EWTSpecWorkerLocation
    """
    Worker image location
    """
    cached: bool | None = True
    """
    Worker cached in local registry, otherwise pull secret is used with auth
    """
    name: Annotated[
        str | None, Field(examples=["myworker:latest"], pattern="^([^:]+):([^:/]+)$")
    ] = None
    """
    Cached image name, otherwise autogenerated from source image

    Example: 'myworker:latest'
    """
    command: Annotated[list[str] | None, Field(min_length=1)] = None
    """
    Override image start command
    """
    config: EWTSpecWorkerConfig | None = None
    """
    Worker image configuration parameters
    """


class EWTSpecWorkerConfig(BaseModel):
    file: EWTSpecWorkerConfigFile | None = None
    """
    Configuration file
    """
    env: list[EWTSpecWorkerConfigEnvItem] | None = None
    """
    Environment variables
    """


class EWTSpecWorkerConfigEnvItem(BaseModel):
    key: Annotated[str, Field(examples=["MY_CFG_ENVVAR"], min_length=1)]
    """
    Variable name

    Example: 'MY_CFG_ENVVAR'
    """
    value: Annotated[str, Field(examples=["42"])]
    """
    Value string

    Example: '42'
    """


class EWTSpecWorkerConfigFile(BaseModel):
    path: Annotated[
        str,
        Field(
            examples=["/var/cache/worker/cfg.ini"], pattern="^((/[a-zA-Z0-9-_\\.]+)+)$"
        ),
    ]
    """
    Mount path of configuration file

    Example: '/var/cache/worker/cfg.ini'
    """
    data: str
    """
    Configuration data
    """


class EWTSpecWorkerLocation(BaseModel):
    protocol: EWTSpecWorkerLocationProtocol | None = "docker"
    """
    Image pull approach
    """
    image: Annotated[
        str,
        Field(
            examples=["busybox:latest"],
            pattern="^([^:/]+://)?([^:/]+(:[0-9]{1,5})?/)?([^:]+):([^:/]+)$",
        ),
    ]
    """
    Image resource location

    Example: 'busybox:latest'
    """
    cred: EWTSpecWorkerLocationCred | None = None
    """
    Credentials for remote image collection
    """


class EWTSpecWorkerLocationCred(BaseModel):
    server: Annotated[
        str | None, Field(pattern="^([^:/]+)(://)([^:/]+(:[0-9]{1,5})?)((/[^/]+)*)/$")
    ] = "https://index.docker.io/v1/"
    """
    Image server prefix
    """
    user: Annotated[str, Field(examples=["admin"], min_length=1)]
    """
    Image registry user

    Example: 'admin'
    """
    secret: Annotated[SecretStr, Field(examples=["myPasswd!007"], min_length=1)]
    """
    Server password or token

    Example: 'myPasswd!007'
    """
    insecure: bool | None = False
    """
    Disable verification of image server's TLS certificate
    """


class EWTSpecWorkerLocationProtocol(StrEnum):
    DOCKER = "docker"
    SECRET = "secret"
    PTX = "ptx"


class EWTStatus(BaseModel):
    state: str | None = None
    """
    Task state from [created | running | finished]
    """
