# generated by datamodel-codegen:
#   filename:  edgeworkertask.json
#   timestamp: 2026-03-18T20:41:31+00:00
#   version:   0.55.0
#   command:   datamodel-codegen --input=schema/edgeworkertask.json --input-file-type=openapi --openapi-scopes=schemas --formatter=isort --keep-model-order --schema-version-mode=strict --enum-field-as-literal=none --field-constraints --use-annotated --naming-strategy=parent-prefixed --enable-version-header --enable-command-header --target-python-version=3.14 --disable-warnings --output app/model/edgeworkertask.py

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, SecretStr


class EdgeWorkerTask(BaseModel):
    spec: Annotated[EdgeWorkerTaskSpec, Field(description='Specification of PTX Edge Task')]
    status: Annotated[EdgeWorkerTaskStatus | None, Field(description='Runtime information')] = None


class EdgeWorkerTaskSpec(BaseModel):
    service: Annotated[EdgeWorkerTaskSpecService | None, Field(
        description='Initiate worker as a service, not a single-executed task')] = None
    data: Annotated[EdgeWorkerTaskSpecData, Field(description='Data collection parameters')]
    worker: Annotated[EdgeWorkerTaskSpecWorker, Field(description='Worker environment parameters')]
    dataspace: Annotated[
        EdgeWorkerTaskSpecDataspace | None, Field(description='Attributes of data exchange via PTX dataspace')] = None


class EdgeWorkerTaskSpecData(BaseModel):
    source: Annotated[EdgeWorkerTaskSpecDataSource, Field(description='Data source location')]
    auth: Annotated[
        EdgeWorkerTaskSpecDataAuth | None, Field(description='Credentials for remote data collection')] = None
    path: Annotated[str | None, Field(description='Absolut path of local directory for collected data',
                                      pattern='^((/[a-zA-Z0-9-_]+)+)/?$')] = '/var/cache/data/'


class EdgeWorkerTaskSpecDataAuth(BaseModel):
    method: Annotated[
        EdgeWorkerTaskSpecDataAuthMethod, Field(description='Used authentication method', examples=['basic'])]
    user: Annotated[str, Field(description='User identification', examples=['admin'], min_length=1)]
    secret: Annotated[SecretStr, Field(description='Secret token or password', examples=['myPasswd!007'], min_length=1)]


class EdgeWorkerTaskSpecDataAuthMethod(StrEnum):
    basic = 'basic'
    digest = 'digest'


class EdgeWorkerTaskSpecDataSource(BaseModel):
    scheme: Annotated[EdgeWorkerTaskSpecDataSourceScheme | None, Field(description='Data collection scheme',
                                                                       examples=['https'])] = None
    location: Annotated[
        str, Field(description='Data resource location', examples=['https://my.api.localhost:8080/data/example.csv'],
                   pattern='^([^:/]+://)?([^:/]+(:[0-9]{1,5})?)?(/.+)$')]


class EdgeWorkerTaskSpecDataSourceScheme(StrEnum):
    file = 'file'
    dir = 'dir'
    http = 'http'
    https = 'https'
    ptx = 'ptx'


class EdgeWorkerTaskSpecDataspace(BaseModel):
    offer: Annotated[EdgeWorkerTaskSpecDataspaceOffer | None, Field(description='PTX dataspace contract info')] = None


class EdgeWorkerTaskSpecDataspaceOffer(BaseModel):
    provider: Annotated[str, Field(description='Data provider ID', min_length=1)]
    consumer: Annotated[str, Field(description='Data consumer ID', min_length=1)]


class EdgeWorkerTaskSpecService(BaseModel):
    enabled: Annotated[bool, Field(description='Enable service creation')]
    interfaces: Annotated[
        list[EdgeWorkerTaskSpecServiceInterface] | None, Field(description='Exposed worker interfaces')] = None


class EdgeWorkerTaskSpecServiceInterface(BaseModel):
    port: Annotated[int, Field(description='Service port', examples=[8080], ge=1, le=65535)]
    public: Annotated[bool | None, Field(description='Enable out-of-cluster access')] = False


class EdgeWorkerTaskSpecWorker(BaseModel):
    source: Annotated[EdgeWorkerTaskSpecWorkerSource, Field(description='Worker image location')]
    cached: Annotated[
        bool | None, Field(description='Worker cached in local registry, otherwise only pull secret is used')] = True
    auth: Annotated[
        EdgeWorkerTaskSpecWorkerAuth | None, Field(description='Credentials for remote image collection')] = None
    image: Annotated[
        str | None, Field(description='Cached image name, otherwise autogenerated', examples=['myworker:latest'],
                          pattern='^([^:]+):([^:/]+)$')] = None
    command: Annotated[list[str] | None, Field(description='Override image start command', min_length=1)] = None
    config: Annotated[
        EdgeWorkerTaskSpecWorkerConfig | None, Field(description='Worker image configuration parameters')] = None


class EdgeWorkerTaskSpecWorkerAuth(BaseModel):
    server: Annotated[str | None, Field(description='Image server prefix',
                                        pattern='^([^:/]+)(://)([^:/]+(:[0-9]{1,5})?)((/[^/]+)*)/$')] = 'https://index.docker.io/v1/'
    user: Annotated[str, Field(description='Image registry user', examples=['admin'], min_length=1)]
    secret: Annotated[SecretStr, Field(description='Server password or token', examples=['myPasswd!007'], min_length=1)]
    insecure: Annotated[
        bool | None, Field(description="Disable verification of image server's TLS certificate")] = False


class EdgeWorkerTaskSpecWorkerConfig(BaseModel):
    file: Annotated[EdgeWorkerTaskSpecWorkerConfigFile | None, Field(description='Configuration file')] = None
    env: Annotated[
        list[EdgeWorkerTaskSpecWorkerConfigEnvItem] | None, Field(description='Environment variables')] = None


class EdgeWorkerTaskSpecWorkerConfigEnvItem(BaseModel):
    key: Annotated[str, Field(description='Variable name', examples=['MY_CFG_ENVVAR'], min_length=1)]
    value: Annotated[str, Field(description='Value string', examples=['42'])]


class EdgeWorkerTaskSpecWorkerConfigFile(BaseModel):
    path: Annotated[str, Field(description='Mount path of configuration file', examples=['/var/cache/worker/cfg.ini'],
                               pattern='^((/[a-zA-Z0-9-_\\.]+)+)$')]
    data: Annotated[str, Field(description='Configuration data')]


class EdgeWorkerTaskSpecWorkerSource(BaseModel):
    scheme: Annotated[EdgeWorkerTaskSpecWorkerSourceScheme | None, Field(description='Image pull approach')] = 'docker'
    location: Annotated[str, Field(description='Image resource location', examples=['busybox:latest'],
                                   pattern='^([^:/]+://)?([^:/]+(:[0-9]{1,5})?/)?([^:]+):([^:/]+)$')]


class EdgeWorkerTaskSpecWorkerSourceScheme(StrEnum):
    docker = 'docker'
    secret = 'secret'
    ptx = 'ptx'


class EdgeWorkerTaskStatus(BaseModel):
    state: Annotated[str | None, Field(description='Task state from [created | running | finished]')] = None
