# @generated by datamodel-codegen:
#   filename:  ptxedgeworker.json
#   version:   0.72.1

from typing import ClassVar
from typing import Annotated
from pydantic import BaseModel as _BaseModel, ConfigDict, Field, RootModel, SecretStr
from enum import StrEnum


class BaseModel(_BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )


class PEWSpecServiceInterface(BaseModel):
    port: Annotated[int, Field(examples=[8080], ge=1, le=65535)]
    """
    Service port

    Example: 8080
    """
    public: bool | None = False
    """
    Enable out-of-cluster access
    """
    secured: bool | None = False
    """
    Apply the same security measures as of the REST-API, e.g., authentication
    """


class PEWSpecService(BaseModel):
    """
    Initiate worker as a service, not a single-executed task
    """

    enabled: bool
    """
    Enable service creation
    """
    interfaces: Annotated[list[PEWSpecServiceInterface] | None, Field(min_length=1)] = (
        None
    )
    """
    Exposed worker interfaces
    """


class PEWSpecDataSrcMethod(StrEnum):
    """
    Data collection method
    """

    FILE = "FILE"
    DIR = "DIR"
    HTTP = "HTTP"
    HTTPS = "HTTPS"
    PTX = "PTX"
    SKIP = "SKIP"


class PEWSpecDataSrcAuthScheme(StrEnum):
    """
    Used authentication method
    """

    BASIC = "BASIC"
    DIGEST = "DIGEST"
    BEARER = "BEARER"


class PEWSpecDataSrcAuth(BaseModel):
    """
    Authentication parameters for remote data collection
    """

    scheme: Annotated[PEWSpecDataSrcAuthScheme, Field(examples=["BASIC"])]
    """
    Used authentication method

    Example: 'BASIC'
    """
    user: Annotated[str, Field(examples=["admin"], min_length=1)]
    """
    User identification

    Example: 'admin'
    """
    secret: Annotated[SecretStr, Field(examples=["myPasswd!007"], min_length=1)]
    """
    Secret token or password

    Example: 'myPasswd!007'
    """
    insecure: bool | None = False
    """
    Disable verification of data server's TLS certificate
    """


class PEWSpecDataSrc(BaseModel):
    """
    Data source location
    """

    method: Annotated[PEWSpecDataSrcMethod, Field(examples=["HTTPS"])]
    """
    Data collection method

    Example: 'HTTPS'
    """
    path: Annotated[
        str | None,
        Field(
            examples=["https://my.api.localhost:8080/data/example.csv"],
            min_length=1,
            pattern="^([^:/]+://)?([^:/]+(:[0-9]{1,5})?)?(/.+)$",
        ),
    ] = None
    """
    Data resource location

    Example: 'https://my.api.localhost:8080/data/example.csv'
    """
    size: Annotated[int | None, Field(ge=1)] = 100
    """
    Requested data size in Megabyte (Mb)
    """
    auth: PEWSpecDataSrcAuth | None = None
    """
    Authentication parameters for remote data collection
    """


class PEWSpecDataDstMethod(StrEnum):
    """
    Data propagation scheme
    """

    LOCAL = "LOCAL"


class PEWSpecDataDst(BaseModel):
    """
    Data destination location
    """

    method: PEWSpecDataDstMethod | None = PEWSpecDataDstMethod.LOCAL
    """
    Data propagation scheme
    """
    path: Annotated[
        str | None, Field(min_length=1, pattern="^((/[a-zA-Z0-9-_]+)+)/?$")
    ] = "/var/cache/data"
    """
    Data resource location
    """


class PEWSpecData(BaseModel):
    """
    Data collection parameters
    """

    src: PEWSpecDataSrc
    """
    Data source location
    """
    dst: PEWSpecDataDst | None = None
    """
    Data destination location
    """


class PEWSpecWorkerLocationMethod(StrEnum):
    """
    Image pull approach
    """

    DOCKER = "DOCKER"
    PTX = "PTX"
    INLINE = "INLINE"
    DATASOURCE = "DATASOURCE"
    SECRET = "SECRET"
    SKIP = "SKIP"


class PEWSpecWorkerLocationCred(BaseModel):
    """
    Credentials for remote image collection
    """

    server: Annotated[
        str | None,
        Field(
            min_length=1, pattern="^([^:/]+)(://)([^:/]+(:[0-9]{1,5})?)((/[^/]+)*)/$"
        ),
    ] = "https://index.docker.io/v1/"
    """
    Image server prefix
    """
    user: Annotated[str, Field(examples=["admin"], min_length=1)]
    """
    Image registry user

    Example: 'admin'
    """
    secret: Annotated[SecretStr, Field(examples=["myPasswd!007"], min_length=1)]
    """
    Server password or token

    Example: 'myPasswd!007'
    """
    insecure: bool | None = False
    """
    Disable verification of image server's TLS certificate
    """


class PEWSpecWorkerLocation(BaseModel):
    """
    Worker image location
    """

    method: Annotated[PEWSpecWorkerLocationMethod, Field(examples=["DOCKER"])]
    """
    Image pull approach

    Example: 'DOCKER'
    """
    image: Annotated[
        str | None,
        Field(
            examples=["busybox:latest"],
            min_length=1,
            pattern="^([^:/]+://)?([^:/]+(:[0-9]{1,5})?/)?([^:]+):([^:/]+)$",
        ),
    ] = None
    """
    Image resource location

    Example: 'busybox:latest'
    """
    cred: PEWSpecWorkerLocationCred | None = None
    """
    Credentials for remote image collection
    """


class PEWSpecWorkerDemands(BaseModel):
    """
    Operating resource demands
    """

    cpu: Annotated[float | None, Field(examples=[1.5], ge=0.5)] = None
    """
    Number of requested vCPU cores

    Example: 1.5
    """
    memory: Annotated[int | None, Field(examples=[1024], ge=1)] = None
    """
    Amount of requested memory in Megabyte (Mb)

    Example: 1024
    """


class PEWSpecWorkerCommandItem(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]
    """
    command & args
    """


class PEWSpecWorkerConfigFile(BaseModel):
    """
    Configuration file
    """

    path: Annotated[
        str,
        Field(
            examples=["/var/cache/worker/cfg.ini"],
            min_length=1,
            pattern="^((/[a-zA-Z0-9-_\\.]+)+)$",
        ),
    ]
    """
    Mount path of configuration file

    Example: '/var/cache/worker/cfg.ini'
    """
    data: str
    """
    Configuration data
    """


class PEWSpecWorkerConfigEnvItem(BaseModel):
    """
    Key-value pairs
    """

    key: Annotated[str, Field(examples=["MY_CFG_ENVVAR"], min_length=1)]
    """
    Variable name

    Example: 'MY_CFG_ENVVAR'
    """
    value: Annotated[str | None, Field(examples=["42"])] = None
    """
    Value string

    Example: '42'
    """


class PEWSpecWorkerConfig(BaseModel):
    """
    Worker image configuration parameters
    """

    file: PEWSpecWorkerConfigFile | None = None
    """
    Configuration file
    """
    env: Annotated[list[PEWSpecWorkerConfigEnvItem] | None, Field(min_length=1)] = None
    """
    Environment variables
    """


class PEWSpecWorker(BaseModel):
    """
    Worker environment parameters
    """

    location: PEWSpecWorkerLocation
    """
    Worker image location
    """
    demands: PEWSpecWorkerDemands | None = None
    """
    Operating resource demands
    """
    cached: bool | None = True
    """
    Worker cached in local registry, otherwise pull secret is used with auth
    """
    name: Annotated[
        str | None,
        Field(examples=["myworker:latest"], min_length=1, pattern="^([^:]+):([^:/]+)$"),
    ] = None
    """
    Cached image name, otherwise autogenerated from source image

    Example: 'myworker:latest'
    """
    command: Annotated[list[PEWSpecWorkerCommandItem] | None, Field(min_length=1)] = (
        None
    )
    """
    Override image start command
    """
    config: PEWSpecWorkerConfig | None = None
    """
    Worker image configuration parameters
    """


class PEWSpecDataspaceExchangeDataProvider(BaseModel):
    """
    Data provider configuration
    """

    offer: Annotated[
        str,
        Field(
            examples=["66d187f4ee71f9f096bae8ca"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ]
    """
    Data offering ID

    Example: '66d187f4ee71f9f096bae8ca'
    """
    resource: Annotated[
        str,
        Field(
            examples=["66d1889cee71f9f096bae98b"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ]
    """
    Data resource ID

    Example: '66d1889cee71f9f096bae98b'
    """


class PEWSpecDataspaceExchangeDataConsumer(BaseModel):
    """
    Data consumer configuration
    """

    offer: Annotated[
        str,
        Field(
            examples=["66d18b79ee71f9f096baecb1"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ]
    """
    Service offering ID

    Example: '66d18b79ee71f9f096baecb1'
    """
    resource: Annotated[
        str,
        Field(
            examples=["66d18bf6ee71f9f096baed58"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ]
    """
    Software resource ID

    Example: '66d18bf6ee71f9f096baed58'
    """


class PEWSpecDataspaceExchangeData(BaseModel):
    """
    Dataspace contract information for data exchange
    """

    contract: Annotated[
        str,
        Field(
            examples=["66db1a6dc29e3ba863a85e0f"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ]
    """
    Dataspace contract ID

    Example: '66db1a6dc29e3ba863a85e0f'
    """
    provider: PEWSpecDataspaceExchangeDataProvider
    """
    Data provider configuration
    """
    consumer: PEWSpecDataspaceExchangeDataConsumer
    """
    Data consumer configuration
    """


class PEWSpecDataspaceExchangeWorkerProvider(PEWSpecDataspaceExchangeDataProvider):
    """
    Data provider configuration
    """


class PEWSpecDataspaceExchangeWorkerConsumer(PEWSpecDataspaceExchangeDataConsumer):
    """
    Data consumer configuration
    """


class PEWSpecDataspaceExchangeWorker(BaseModel):
    """
    Dataspace contract information for worker exchange
    """

    contract: Annotated[
        str,
        Field(
            examples=["66db1a6dc29e3ba863a85e0f"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ]
    """
    Dataspace contract ID

    Example: '66db1a6dc29e3ba863a85e0f'
    """
    provider: PEWSpecDataspaceExchangeWorkerProvider
    """
    Data provider configuration
    """
    consumer: PEWSpecDataspaceExchangeWorkerConsumer
    """
    Data consumer configuration
    """


class PEWSpecDataspaceExchange(BaseModel):
    """
    Attributes of data exchange via PTX dataspace
    """

    data: PEWSpecDataspaceExchangeData | None = None
    """
    Dataspace contract information for data exchange
    """
    worker: PEWSpecDataspaceExchangeWorker | None = None
    """
    Dataspace contract information for worker exchange
    """


class PEWSpecDataspacePrivacyZone(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]
    """
    Privacy zone ID
    """


class PEWSpecDataspacePrivacy(BaseModel):
    """
    Privacy zone restriction policies
    """

    required: bool | None = True
    """
    Demands PTX-edge specific scheduler
    """
    zones: Annotated[list[PEWSpecDataspacePrivacyZone] | None, Field(min_length=1)] = (
        None
    )
    """
    List of privacy zones as node selection criteria
    """


class PEWSpecDataspace(BaseModel):
    """
    PTX dataspace-related configuration
    """

    exchange: PEWSpecDataspaceExchange | None = None
    """
    Attributes of data exchange via PTX dataspace
    """
    privacy: PEWSpecDataspacePrivacy | None = None
    """
    Privacy zone restriction policies
    """


class PEWSpec(BaseModel):
    """
    Specification of PTX Edge Worker
    """

    service: PEWSpecService | None = None
    """
    Initiate worker as a service, not a single-executed task
    """
    data: PEWSpecData
    """
    Data collection parameters
    """
    worker: PEWSpecWorker
    """
    Worker environment parameters
    """
    dataspace: PEWSpecDataspace | None = None
    """
    PTX dataspace-related configuration
    """


class PEWStatus(BaseModel):
    """
    Runtime information
    """

    state: str | None = None
    """
    Task state from [created | running | finished]
    """


class PEW(BaseModel):
    # Resource specification parameters from CustomResourceDefinition
    group: ClassVar[str] = "dataspace.ptx.org"
    version: ClassVar[str] = "v1alpha1"
    kind: ClassVar[str] = "PtxEdgeWorker"
    plural: ClassVar[str] = "ptxedgeworkers"
    singular: ClassVar[str] = "ptxedgeworker"
    # Unique resource identification
    SELECTOR: ClassVar[tuple[str, str, str]] = (group, version, plural)
    #
    """
    PTX Edge Worker description
    """
    spec: PEWSpec
    """
    Specification of PTX Edge Worker
    """
    status: PEWStatus | None = None
    """
    Runtime information
    """
