# @generated by datamodel-codegen:
#   filename:  ptxedgeworker.json
#   version:   0.72.1

from typing import ClassVar
from typing import Annotated
from pydantic import BaseModel as _BaseModel, ConfigDict, Field, SecretStr
from enum import StrEnum


class BaseModel(_BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )


class PEWSpecServiceInterface(BaseModel):
    port: Annotated[int, Field(examples=[8080], ge=1, le=65535)]
    """
    Service port

    Example: 8080
    """
    public: bool | None = False
    """
    Enable out-of-cluster access
    """
    secured: bool | None = False
    """
    Apply the same security measures as of the REST-API, e.g., authentication
    """


class PEWSpecService(BaseModel):
    """
    Initiate worker as a service, not a single-executed task
    """

    enabled: bool
    """
    Enable service creation
    """
    interfaces: list[PEWSpecServiceInterface] | None = None
    """
    Exposed worker interfaces
    """


class PEWSpecDataSrcScheme(StrEnum):
    """
    Data collection scheme
    """

    FILE = "file"
    DIR = "dir"
    HTTP = "http"
    HTTPS = "https"
    PTX = "ptx"


class PEWSpecDataSrcAuthMethod(StrEnum):
    """
    Used authentication method
    """

    BASIC = "basic"
    DIGEST = "digest"
    BEARER = "bearer"


class PEWSpecDataSrcAuth(BaseModel):
    """
    Authentication parameters for remote data collection
    """

    method: Annotated[PEWSpecDataSrcAuthMethod, Field(examples=["basic"])]
    """
    Used authentication method

    Example: 'basic'
    """
    user: Annotated[str, Field(examples=["admin"], min_length=1)]
    """
    User identification

    Example: 'admin'
    """
    secret: Annotated[SecretStr, Field(examples=["myPasswd!007"], min_length=1)]
    """
    Secret token or password

    Example: 'myPasswd!007'
    """


class PEWSpecDataSrc(BaseModel):
    """
    Data source location
    """

    scheme: Annotated[PEWSpecDataSrcScheme | None, Field(examples=["https"])] = None
    """
    Data collection scheme

    Example: 'https'
    """
    path: Annotated[
        str,
        Field(
            examples=["https://my.api.localhost:8080/data/example.csv"],
            pattern="^([^:/]+://)?([^:/]+(:[0-9]{1,5})?)?(/.+)$",
        ),
    ]
    """
    Data resource location

    Example: 'https://my.api.localhost:8080/data/example.csv'
    """
    auth: PEWSpecDataSrcAuth | None = None
    """
    Authentication parameters for remote data collection
    """


class PEWSpecDataDstScheme(StrEnum):
    """
    Data propagation scheme
    """

    LOCAL = "local"


class PEWSpecDataDst(BaseModel):
    """
    Data destination location
    """

    scheme: PEWSpecDataDstScheme | None = PEWSpecDataDstScheme.LOCAL
    """
    Data propagation scheme
    """
    path: Annotated[str | None, Field(pattern="^((/[a-zA-Z0-9-_]+)+)$")] = (
        "/var/cache/data"
    )
    """
    Data resource location
    """


class PEWSpecData(BaseModel):
    """
    Data collection parameters
    """

    src: PEWSpecDataSrc
    """
    Data source location
    """
    dst: PEWSpecDataDst | None = None
    """
    Data destination location
    """


class PEWSpecWorkerLocationProtocol(StrEnum):
    """
    Image pull approach
    """

    DOCKER = "docker"
    SECRET = "secret"
    PTX = "ptx"


class PEWSpecWorkerLocationCred(BaseModel):
    """
    Credentials for remote image collection
    """

    server: Annotated[
        str | None, Field(pattern="^([^:/]+)(://)([^:/]+(:[0-9]{1,5})?)((/[^/]+)*)/$")
    ] = "https://index.docker.io/v1/"
    """
    Image server prefix
    """
    user: Annotated[str, Field(examples=["admin"], min_length=1)]
    """
    Image registry user

    Example: 'admin'
    """
    secret: Annotated[SecretStr, Field(examples=["myPasswd!007"], min_length=1)]
    """
    Server password or token

    Example: 'myPasswd!007'
    """
    insecure: bool | None = False
    """
    Disable verification of image server's TLS certificate
    """


class PEWSpecWorkerLocation(BaseModel):
    """
    Worker image location
    """

    protocol: PEWSpecWorkerLocationProtocol | None = (
        PEWSpecWorkerLocationProtocol.DOCKER
    )
    """
    Image pull approach
    """
    image: Annotated[
        str,
        Field(
            examples=["busybox:latest"],
            pattern="^([^:/]+://)?([^:/]+(:[0-9]{1,5})?/)?([^:]+):([^:/]+)$",
        ),
    ]
    """
    Image resource location

    Example: 'busybox:latest'
    """
    cred: PEWSpecWorkerLocationCred | None = None
    """
    Credentials for remote image collection
    """


class PEWSpecWorkerConfigFile(BaseModel):
    """
    Configuration file
    """

    path: Annotated[
        str,
        Field(
            examples=["/var/cache/worker/cfg.ini"], pattern="^((/[a-zA-Z0-9-_\\.]+)+)$"
        ),
    ]
    """
    Mount path of configuration file

    Example: '/var/cache/worker/cfg.ini'
    """
    data: str
    """
    Configuration data
    """


class PEWSpecWorkerConfigEnvItem(BaseModel):
    """
    Key-value pairs
    """

    key: Annotated[str, Field(examples=["MY_CFG_ENVVAR"], min_length=1)]
    """
    Variable name

    Example: 'MY_CFG_ENVVAR'
    """
    value: Annotated[str, Field(examples=["42"])]
    """
    Value string

    Example: '42'
    """


class PEWSpecWorkerConfig(BaseModel):
    """
    Worker image configuration parameters
    """

    file: PEWSpecWorkerConfigFile | None = None
    """
    Configuration file
    """
    env: list[PEWSpecWorkerConfigEnvItem] | None = None
    """
    Environment variables
    """


class PEWSpecWorker(BaseModel):
    """
    Worker environment parameters
    """

    location: PEWSpecWorkerLocation
    """
    Worker image location
    """
    cached: bool | None = True
    """
    Worker cached in local registry, otherwise pull secret is used with auth
    """
    name: Annotated[
        str | None, Field(examples=["myworker:latest"], pattern="^([^:]+):([^:/]+)$")
    ] = None
    """
    Cached image name, otherwise autogenerated from source image

    Example: 'myworker:latest'
    """
    command: Annotated[list[str] | None, Field(min_length=1)] = None
    """
    Override image start command
    """
    config: PEWSpecWorkerConfig | None = None
    """
    Worker image configuration parameters
    """


class PEWSpecDataspaceExchangeProvider(BaseModel):
    """
    Data provider configuration
    """

    offer: Annotated[
        str,
        Field(
            examples=["66d187f4ee71f9f096bae8ca"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ]
    """
    Data offering ID

    Example: '66d187f4ee71f9f096bae8ca'
    """
    resource: Annotated[
        str | None,
        Field(
            examples=["66d1889cee71f9f096bae98b"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ] = None
    """
    Data resource ID

    Example: '66d1889cee71f9f096bae98b'
    """


class PEWSpecDataspaceExchangeConsumer(BaseModel):
    """
    Data consumer configuration
    """

    offer: Annotated[
        str,
        Field(
            examples=["66d18b79ee71f9f096baecb1"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ]
    """
    Service offering ID

    Example: '66d18b79ee71f9f096baecb1'
    """
    resource: Annotated[
        str | None,
        Field(
            examples=["66d18bf6ee71f9f096baed58"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ] = None
    """
    Software resource ID

    Example: '66d18bf6ee71f9f096baed58'
    """


class PEWSpecDataspaceExchange(BaseModel):
    """
    Attributes of data exchange via PTX dataspace
    """

    contract: Annotated[
        str,
        Field(
            examples=["66db1a6dc29e3ba863a85e0f"],
            min_length=1,
            pattern="^[0-9a-fA-F]+$",
        ),
    ]
    """
    Dataspace contract ID

    Example: '66db1a6dc29e3ba863a85e0f'
    """
    provider: PEWSpecDataspaceExchangeProvider | None = None
    """
    Data provider configuration
    """
    consumer: PEWSpecDataspaceExchangeConsumer | None = None
    """
    Data consumer configuration
    """


class PEWSpecDataspace(BaseModel):
    """
    PTX dataspace-related configuration
    """

    exchange: PEWSpecDataspaceExchange
    """
    Attributes of data exchange via PTX dataspace
    """


class PEWSpec(BaseModel):
    """
    Specification of PTX Edge Worker
    """

    service: PEWSpecService | None = None
    """
    Initiate worker as a service, not a single-executed task
    """
    data: PEWSpecData
    """
    Data collection parameters
    """
    worker: PEWSpecWorker
    """
    Worker environment parameters
    """
    dataspace: PEWSpecDataspace | None = None
    """
    PTX dataspace-related configuration
    """


class PEWStatus(BaseModel):
    """
    Runtime information
    """

    state: str | None = None
    """
    Task state from [created | running | finished]
    """


class PEW(BaseModel):
    # Resource specification parameters from CustomResourceDefinition
    group: ClassVar[str] = "dataspace.ptx.org"
    version: ClassVar[str] = "v1alpha1"
    kind: ClassVar[str] = "PtxEdgeWorker"
    plural: ClassVar[str] = "ptxedgeworkers"
    singular: ClassVar[str] = "ptxedgeworker"
    # Unique resource identification
    SELECTOR: ClassVar[tuple[str, str, str]] = (group, version, plural)
    #
    """
    PTX Edge Worker description
    """
    spec: PEWSpec
    """
    Specification of PTX Edge Worker
    """
    status: PEWStatus | None = None
    """
    Runtime information
    """
