# Copyright 2025 Janos Czentye
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by fastapi-codegen:
#   filename:  ../spec/openapi_design.json
#   timestamp: 2025-05-20T13:46:51+00:00
from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, Field, RootModel


class VersionResponse(BaseModel):
    """Versions of the REST-API component"""
    api: str = Field(..., title='Api')
    framework: str = Field(..., title='Framework')


########################################################################################################################

class ExecutionMetrics(BaseModel):
    """Collected execution metrics"""
    elapsedTime: int = Field(None, ge=0, description='Elapsed time of the function', examples=[42])
    ret: int = Field(None, ge=0, le=255, description='Return value of the function', examples=[0])


class ExecutionResult(BaseModel):
    """The result of the function execution on data"""
    data: str = Field(..., description='Unique reference/ID of the data', examples=['Data42'])
    function: str = Field(..., description='Unique reference/ID of the function to be applied to the private data',
                          examples=['FunctionData42'], )
    uuid: UUID = Field(..., description='Unique operation identifier',
                       examples=['11111111-2222-3333-4444-555555555555'])
    metrics: ExecutionMetrics = None


class PrivateExecutionResult(BaseModel):
    """The result of the function execution on data"""
    function: str = Field(..., description='Unique reference/ID of the function to be applied to the private data',
                          examples=['FunctionData42'])
    private_data: str = Field(..., description='Unique reference/ID of the data', examples=['Data42'])
    uuid: UUID = Field(..., description='Unique operation identifier',
                       examples=['11111111-2222-3333-4444-555555555555'])
    metrics: ExecutionMetrics = None


########################################################################################################################

class Metadata(RootModel[dict[str, str | int]]):
    """Arbitrary key-value pairs"""
    root: dict[str, str | int] = None


class ExecutionRequestBody(BaseModel):
    """Function execution parameters"""
    data: str = Field(..., description='Unique reference/ID of the data', examples=['Data42'])
    data_contract: str = Field(..., description='Unique contract ID', examples=['Contract42'])
    func_contract: str = Field(..., description='Unique contract ID', examples=['Contract42'])
    function: str = Field(..., description='Unique reference/ID of the function to be applied to the private data',
                          examples=['FunctionData42'])
    metadata: Metadata = None


class PrivateExecutionRequestBody(BaseModel):
    """Function execution parameters"""
    consent: str = Field(..., description='Unique consent ID', examples=['Consent42'])
    data_contract: str = Field(..., description='Unique contract ID', examples=['Contract42'])
    func_contract: str = Field(..., description='Unique contract ID', examples=['Contract42'])
    function: str = Field(..., description='Unique reference/ID of the function to be applied to the private data',
                          examples=['FunctionData42'])
    private_data: str = Field(..., description='Unique reference/ID of the data', examples=['Data42'])
    token: str = Field(..., description="Unique token created by the DataProvider related to the user's consent",
                       examples=['Token42'])
    metadata: Metadata = None
