name: exchange
services:
  ######################################################################################################################

  # Shared DB for PDC instances
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: no # fail fast
    security_opt:
      - no-new-privileges:true
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    command: [ "--logpath", "/var/log/mongodb/mongod.log" ]
    configs:
      - source: cfg-mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        mode: 0444
    volumes:
      - vol-mongo:/data/db
    networks:
      - nw-mongo
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 500m
    healthcheck:
      test: [ 'CMD', 'mongosh', '-u=admin', '-p=admin', '--authenticationDatabase=admin', "--eval=db.adminCommand('ping')" ]
      start_period: 15s
      interval: 5m

  ######################################################################################################################

  # PDC instances
  pdc-provider:
    container_name: pdc-provider
    image: dataspace-connector:latest
    pull_policy: never
    restart: no # fail fast
    init: true  # handle signals
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.services.pdc-provider.loadbalancer.server.port=3000"
    #  - "traefik.http.routers.datasource.entrypoints=web"
    #  - "traefik.http.routers.datasource.rule=PathPrefix(`/datasource/pdc`)"
    #  - "traefik.http.routers.datasource.middlewares=no-data-path@docker"
    #  - "traefik.http.middlewares.no-data-path.stripprefix.prefixes=/datasource/pdc"
    environment:
      MONGO_URI: mongodb://pdc:pdc@mongodb:27017/pdc-provider?authSource=pdc-provider&appName=pdc-provider
    configs:
      - source: cfg-npmrc
        target: /root/.npmrc
      - source: cfg-pdc-provider.json
        target: /usr/src/app/src/config.json
      - source: cfg-pdc-provider.env
        target: /usr/src/app/.env
    networks:
      - nw-mongo
      - nw-proxy
      - nw-provider
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 700m
    healthcheck:
      test: [ 'CMD', 'curl', '-o', '/dev/null', '-SsfI', 'http://localhost:3000' ]
      start_period: 15s
      interval: 5m
    depends_on:
      mongodb:
        condition: service_healthy

  pdc-consumer:
    container_name: pdc-consumer
    image: dataspace-connector:latest
    pull_policy: never
    restart: no # fail fast
    init: true # handle signals
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.services.pdc-consumer.loadbalancer.server.port=3000"
    #  - "traefik.http.routers.consumer.entrypoints=web"
    #  - "traefik.http.routers.consumer.rule=PathPrefix(`/service/pdc`)"
    #  - "traefik.http.routers.consumer.middlewares=no-service-path@docker"
    #  - "traefik.http.middlewares.no-service-path.stripprefix.prefixes=/service/pdc"
    environment:
      MONGO_URI: mongodb://pdc:pdc@mongodb:27017/pdc-consumer?authSource=pdc-consumer&appName=pdc-consumer
    configs:
      - source: cfg-npmrc
        target: /root/.npmrc
      - source: cfg-pdc-consumer.json
        target: /usr/src/app/src/config.json
      - source: cfg-pdc-consumer.env
        target: /usr/src/app/.env
    networks:
      - nw-mongo
      - nw-proxy
      - nw-consumer
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 700m
    healthcheck:
      test: [ 'CMD', 'curl', '-o', '/dev/null', '-SsfI', 'http://localhost:3000' ]
      start_period: 15s
      interval: 5m
    depends_on:
      mongodb:
        condition: service_healthy

  ######################################################################################################################

  traefik-proxy:
    container_name: traefik-proxy
    image: traefik:v3.7
    restart: no # fail fast
    user: 1001:1001
    security_opt:
      - no-new-privileges:true
    command:
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
      - "--ping=true"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entryPoints.web.address=:80"
      - "--providers.file.filename=/etc/traefik/routes.yml"
      - "--providers.file.watch=false"
      #- "--providers.docker=true"
      #- "--providers.docker.exposedbydefault=false"
      #- "--providers.docker.network=nw-proxy"
    configs:
      - source: cfg-traefik-routers.yaml
        target: /etc/traefik/routes.yml
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"  # debug web dashboard
    networks:
      - nw-proxy
      - nw-tunnel
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 50m
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      start_period: 5s
      interval: 1m
    depends_on:
      pdc-provider:
        condition: service_healthy
      pdc-consumer:
        condition: service_healthy

  # Reverse HTTP(S) tunnels to local PDC instances
  ngrok-tunnel:
    container_name: ngrok-tunnel
    image: ngrok/ngrok:alpine
    restart: no # fail fast
    user: 1001:1001
    security_opt:
      - no-new-privileges:true
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN:?}
    command: [ 'http', 'http://traefik-proxy:80', "--url=${NGROK_DOMAIN:?}", '--log=stdout' ]
    ports:
      - "4040:4040" # debug web dashboard
    networks:
      - nw-tunnel
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 50m
    healthcheck:
      test: [ 'CMD-SHELL', 'ngrok diagnose >/dev/null' ]
      start_period: 5s
      interval: 1m
    depends_on:
      traefik-proxy:
        condition: service_healthy

  ######################################################################################################################

  # Additional packet profilers
  sniffer-provider:
    container_name: sniffer-provider
    image: alpine/tshark:latest
    pull_policy: never
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp  # Enable temporary file creation in read-only file system
    build:
      context: .
      dockerfile_inline: |
        FROM alpine:latest
        RUN apk --no-cache add tshark
    restart: no # fail fast
    cap_add:
      - NET_RAW
      - NET_ADMIN
    command: [ 'tshark', '-i', 'eth0', '-Y', 'http', '-O', 'http', '-V' ]
    network_mode: service:api-provider
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 100m
    depends_on:
      - api-provider
    profiles:
      - extra

  sniffer-consumer:
    container_name: sniffer-consumer
    image: alpine/tshark:latest
    pull_policy: never
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp  # Enable temporary file creation in read-only file system
    build:
      context: .
      no_cache: true
      dockerfile_inline: "FROM alpine/tshark:latest"
      additional_contexts:
        alpine/tshark: service:sniffer-provider
    restart: no # fail fast
    cap_add:
      - NET_RAW
      - NET_ADMIN
    command: [ 'tshark', '-i', 'eth0', '-Y', 'http', '-O', 'http', '-V' ]
    network_mode: service:api-consumer
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 100m
    depends_on:
      - api-consumer
    profiles:
      - extra

########################################################################################################################

configs:
  # Define users for PDC's own collection
  cfg-mongo-init.js:
    content: |
      db.getSiblingDB('pdc-provider').createUser({
        user: 'pdc',
        pwd: 'pdc',
        roles: [{ role: 'readWrite',
                    db: 'pdc-provider' }]
      });
      db.getSiblingDB('pdc-consumer').createUser({
        user: 'pdc',
        pwd: 'pdc',
        roles: [{ role: 'readWrite', 
                    db: 'pdc-consumer' }]
      });

  # Define provider PDC's main configuration
  cfg-pdc-provider.json:
    content: |
      {
        "endpoint": "https://${NGROK_DOMAIN:?}/datasource/pdc",
        "serviceKey": "${DS_PDC_SERVICE_KEY:?}",
        "secretKey": "${DS_PDC_SECRET_KEY:?}",
        "catalogUri": "https://api.visionstrust.com/v1/",
        "contractUri": "https://contract.visionstrust.com/",
        "consentUri": "https://consent.visionstrust.com/v1",
        "credentials": [
          {
            "_id": "test-auth-basic",
            "type": "api-key",
            "key": "Authorization",
            "value": "Basic YWRtaW46YWRtaW4="
          }
        ],
        "expressLimitSize": "10mb",
        "serviceChainAdapter": false,
        "serviceChainAdapterTimeout": 3000
      }

  cfg-pdc-provider.env:
    content: |
      NODE_ENV=production
      PORT=3000
      SESSION_SECRET=6OEVPVF73INhElUq
      SESSION_COOKIE_EXPIRATION=24000
      WINSTON_LOGS_MAX_FILES=1d
      WINSTON_LOGS_MAX_SIZE=20m
      JWT_BEARER_TOKEN_EXPIRATION=1h
      JWT_REFRESH_TOKEN_EXPIRATION=3h
      EXCHANGE_TRIGGER_API_KEY=${DS_PDC_EXCHANGE_TRIGGER_API_KEY:-}
      EXCHANGE_TIMEOUT=60

  # Define consumer PDC's main configuration
  cfg-npmrc:
    content: |
      update-notifier=false

  cfg-pdc-consumer.json:
    content: |
      {
        "endpoint": "https://${NGROK_DOMAIN:?}/service/pdc",
        "serviceKey": "${PDC_SERVICE_KEY:?}",
        "secretKey": "${PDC_SECRET_KEY:?}",
        "catalogUri": "https://api.visionstrust.com/v1/",
        "contractUri": "https://contract.visionstrust.com/",
        "consentUri": "https://consent.visionstrust.com/v1",
        "credentials": [],
        "expressLimitSize": "10mb",
        "serviceChainAdapter": false,
        "serviceChainAdapterTimeout": 3000
      }

  cfg-pdc-consumer.env:
    content: |
      NODE_ENV=production
      PORT=3000
      SESSION_SECRET=6OEVPVF73INhElUq
      SESSION_COOKIE_EXPIRATION=24000
      WINSTON_LOGS_MAX_FILES=14d
      WINSTON_LOGS_MAX_SIZE=20m
      JWT_BEARER_TOKEN_EXPIRATION=1h
      JWT_REFRESH_TOKEN_EXPIRATION=3h
      EXCHANGE_TRIGGER_API_KEY=${PDC_EXCHANGE_TRIGGER_API_KEY:-}
      EXCHANGE_TIMEOUT=60

  cfg-traefik-routers.yaml:
    content: |
      http:
        routers:
          datasource:
            service: pdc-provider
            rule: PathPrefix(`/datasource/pdc`)
            middlewares: no-pdc-prefix@file
            entrypoints:
              - web
          consumer:
            service: pdc-consumer
            rule: PathPrefix(`/service/pdc`)
            middlewares: no-pdc-prefix@file
            entrypoints:
              - web
        services:
          pdc-provider:
            loadbalancer:
              servers:
                - url: http://pdc-provider:3000
          pdc-consumer:
            loadbalancer:
              servers:
                - url: http://pdc-consumer:3000
        middlewares:
          no-pdc-prefix:
            stripprefix:
              prefixes:
                - /datasource/pdc
                - /service/pdc

########################################################################################################################

volumes:
  # Persisted db volume
  vol-mongo:
    name: vol-mongo
    external: false

########################################################################################################################

networks:
  # MongoDB local network without external access
  nw-mongo:
    name: nw-mongo
    internal: true
  # Participants' local networks
  nw-provider:
    name: nw-provider
    internal: true
  nw-consumer:
    name: nw-consumer
    internal: true
  nw-proxy:
    name: nw-proxy
  nw-tunnel:
    name: nw-tunnel