include:
  - basic-infra.yaml
services:
  # Main datasource API serving data with different extensions and authentication
  api-provider:
    container_name: api-provider
    image: busybox:latest
    #image: joseluisq/static-web-server:2
    restart: no # fail fast
    labels:
      setup: exchange
    init: true
    working_dir: /usr/src/app/static
    command: [ 'httpd', '-vv', '-f', '-u', '1001:1001', '-p', '0.0.0.0:8080', '-h', './', '-r', 'Provider API' ]
    #command: [ '-a=0.0.0.0', '-p=8080', '-d=/usr/src/app/static/', '-g=info', '--log-remote-address' ]
    configs:
      - source: cfg-httpd.conf
        target: /etc/httpd.conf
      - source: cfg-hz
        target: /usr/src/app/static/healthz
      - source: dp0.json
        target: /usr/src/app/static/dp0.json
        uid: '1001'
        gid: '1001'
        mode: 0444
      - source: dp0-data.csv
        target: /usr/src/app/static/dp0/data.csv
        uid: '1001'
        gid: '1001'
        mode: 0444
    networks:
      - nw-provider
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:8080/healthz' ]
      start_period: 5s
      interval: 5m
    depends_on:
      ngrok-tunnel:
        condition: service_healthy

  # Main API accepting any GET/POST and returning static JSON
  api-provider-status:
    container_name: api-provider-status
    image: busybox:latest
    restart: no # fail fast
    labels:
      setup: exchange
    configs:
      - source: provider-status-hook.sh
        target: /usr/app/entrypoint.sh
        mode: 0555
    entrypoint: /usr/app/entrypoint.sh
    stop_signal: SIGKILL
    networks:
      - nw-provider
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:8080/healthz' ]
      start_period: 5s
      interval: 5m
    depends_on:
      api-provider:
        condition: service_healthy

  ######################################################################################################################

  # Main data consumer API accepting any callbacks and returning static JSON
  api-consumer:
    container_name: api-consumer
    image: busybox:latest
    restart: no # fail fast
    labels:
      setup: exchange
    configs:
      - source: consumer-server.sh
        target: /usr/app/entrypoint.sh
        mode: 0555
    entrypoint: /usr/app/entrypoint.sh
    stop_signal: SIGKILL
    networks:
      - nw-consumer
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:8080/healthz' ]
      start_period: 5s
      interval: 5m
    depends_on:
      ngrok-tunnel:
        condition: service_healthy
      api-provider:
        condition: service_healthy

  ## Main data consumer API accepting any PDC callbacks and returning env data
  #api-consumer:
  #  container_name: api-consumer
  #  image: traefik/whoami:latest
  #  restart: no # fail fast
  #  labels:
  #    setup: exchange
  #  command: [ '--port=8080', '--name=consumer', '--verbose' ]
  #  networks:
  #    - nw-consumer
  #  depends_on:
  #    pdc-consumer:
  #      condition: service_healthy
  #    api-provider:
  #      condition: service_healthy

########################################################################################################################

configs:
  # Provider API config
  cfg-hz:
    content: "OK"
  # - set proper mime type for non-HTML responses
  # - set basic authentication for specific path
  cfg-httpd.conf:
    content: |
      .json:application/json;charset=utf-8
      .csv:text/csv;charset=utf-8
      /dp0/:admin:admin
  # Dataset and resource descriptor for provider (Datasource)
  dp0.json:
    content: |
      {
        "type": "REST",
        "content": {
          "url": "http://provider-api:8080/dp0/data.csv",
          "auth": {
            "scheme": "http",
            "user": "admin",
            "secret": "admin",
            "insecure": false,
          }
        }
      }
  dp0-data.csv:
    content: |
      Name,Age,Department
      Alice,30,Engineering
      Bob,25,Marketing
      Charlie,35,Sales

  # Simple consumer API config
  provider-status-hook.sh:
    content: |
      #!/usr/bin/env sh
      while true; do
        echo -e '\n\nWaiting for webhooks...'
        printf 'HTTP/1.1 200 OK\r\n\r\n%s\n' | nc -vnl -p 8080;
      done

  # Simple consumer API config
  consumer-server.sh:
    content: |
      #!/usr/bin/env sh
      while true; do
        echo -e '\n\nWaiting for connections...'
        body="{ \"timestamp\": \"$$(date +%s)\", \"participant\": \"CONSUMER\", \"status\": \"OK\" }";
        len="$$(printf '%s\n' "$${body}" | wc -c)";
        resp='HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: %s\r\n\r\n%s\n'
        printf "$${resp}" "$${len}" "$${body}" | nc -vnl -p 8080;
      done