openapi: 3.0.0
info:
  title: PTX Edge Computing REST-API
  version: 1.0.0
  contact:
    email: czentye.janos@vik.bme.hu
  description: >-
    The Edge Computing (Decentralized AI processing) BB-02 provides value-added
    services exploiting an underlying distributed edge computing infrastructure.
paths:
  /requestEdgeProc:
    post:
      summary: Execute function on data
      description: ''
      operationId: customer_api.request_edge_proc
      responses:
        "202":
          description: Function deployment accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
        400:
          description: Malformed deployment request
        403:
          description: Request prohibited by contract/consent
        404:
          description: Execution request parameters not found
        408:
          description: Function deployment timeout
        412:
          description: Undeployable request due to privacy zone restriction
        "415":
          description: Unsupported request format
        500:
          description: Unexpected error
        503:
          description: Insufficient compute resources or unavailable deployment service
      tags:
        - customerAPI
      parameters: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecutionRequestBody'
  /requestPrivacyEdgeProc:
    post:
      summary: Execute function on private data
      description: ''
      operationId: customer_api.request_privacy_edge_proc
      responses:
        "202":
          description: Function deployment accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateExecutionResult'
        400:
          description: Malformed deployment request
        401:
          description: Unauthorized request due to invalid token
        403:
          description: Request prohibited by contract/consent
        404:
          description: Execution request parameters not found
        408:
          description: Function deployment timeout
        412:
          description: Undeployable request due to privacy zone restriction
        "415":
          description: Unsupported request format
        500:
          description: Unexpected error
        503:
          description: Insufficient compute resources or unavailable deployment service
      tags:
        - customerAPI
      parameters: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrivateExecutionRequestBody'
externalDocs:
  url: 'https://github.com/Prometheus-X-association/edge-computing'
components:
  schemas:
    Metadata:
      type: object
      description: Arbitrary key-value pairs
      additionalProperties:
        oneOf:
          - type: string
          - type: integer
      example:
        timeout: 42
        privacy-zone: zone-A
        CPU-demand: 42
    ExecutionRequestBody:
      type: object
      description: Function execution parameters
      required:
        - function
        - data
        - data_contract
        - func_contract
      properties:
        function:
          type: string
          description: Unique reference/ID of the function to be applied to the private data
          example: FunctionData42
        data:
          type: string
          description: Unique reference/ID of the data
          example: Data42
        data_contract:
          type: string
          description: Unique contract ID
          example: Contract42
        func_contract:
          type: string
          description: Unique contract ID
          example: Contract42
        metadata:
          $ref: '#/components/schemas/Metadata'
    PrivateExecutionRequestBody:
      type: object
      description: Function execution parameters
      required:
        - function
        - private_data
        - data_contract
        - func_contract
        - consent
        - token
      properties:
        function:
          type: string
          description: Unique reference/ID of the function to be applied to the private data
          example: FunctionData42
        private_data:
          type: string
          description: Unique reference/ID of the data
          example: Data42
        data_contract:
          type: string
          description: Unique contract ID
          example: Contract42
        func_contract:
          type: string
          description: Unique contract ID
          example: Contract42
        consent:
          type: string
          description: Unique consent ID
          example: Consent42
        token:
          type: string
          description: Unique token created by the DataProvider related to the user's consent
          example: Token42
        metadata:
          $ref: '#/components/schemas/Metadata'
    ExecutionMetrics:
      type: object
      description: Collected execution metrics
      properties:
        ret:
          type: integer
          description: Return value of the function
          example: 0
          minimum: 0
          maximum: 255
        elapsedTime:
          type: integer
          description: Elapsed time of the function
          minimum: 0
          example: 42
    ExecutionResult:
      type: object
      description: The result of the function execution on data
      required:
        - uuid
        - function
        - data
      properties:
        uuid:
          type: string
          description: Unique operation identifier
          format: uuid
          example: 11111111-2222-3333-4444-555555555555
        function:
          type: string
          description: Unique reference/ID of the function to be applied to the private data
          example: FunctionData42
        data:
          type: string
          description: Unique reference/ID of the data
          example: Data42
        metrics:
          $ref: '#/components/schemas/ExecutionMetrics'
    PrivateExecutionResult:
      type: object
      description: The result of the function execution on data
      required:
        - uuid
        - function
        - private_data
      properties:
        uuid:
          type: string
          description: Unique operation identifier
          format: uuid
          example: 11111111-2222-3333-4444-555555555555
        function:
          type: string
          description: Unique reference/ID of the function to be applied to the private data
          example: FunctionData42
        private_data:
          type: string
          description: Unique reference/ID of the data
          example: Data42
        metrics:
          $ref: '#/components/schemas/ExecutionMetrics'
  links: { }
  callbacks: { }
tags:
  - name: customerAPI
    description: Customer-facing API (EdgeAPI)
  - name: connectorAPI
    description: Connector-facing API (PrivacyPreservingPDC)
security: [ ]
servers:
  - url: /ptx-edge/v1
    description: PTX Edge Computing

