apiVersion: dataspace.ptx.org/v1alpha1
kind: PtxEdgeWorker
metadata:
  name: ${DP1}
  namespace: ${PTX}
  labels:
    app.kubernetes.io/name: ${DP1}
    env: ${ENV}
spec:
  service:
    enabled: true
    interfaces:
      - port: 8000
      - port: 5000
  data:
    src:
      method: ${DP1_DATA_METHOD}
      path: ${DP1_DATA_SRC}
      auth:
        scheme: BASIC
        user: ${DS_API_USER}
        secret: ${DS_API_PASSWORD}
        insecure: ${DS_API_INSECURE}
      size: 100
    dst:
      method: LOCAL
      path: "/var/cache/data/"
  worker:
    src:
      method: SKIP
      image: ${DP1_IMG}
    config:
      env:
        - key: mlflow_tracking_uri_internal
          value: "${DP1_MLFLOW_INT}"
        - key: mlflow_tracking_uri_organizational
          value: "${DP1_MLFLOW_ORG}"
    demands:
      cpu: 1.0
      memory: 3000
  dataspace:
    privacy:
      required: true
      zones:
        - name: "${PZ_DATA_1}"